services:
  postgres:
    image: postgres:17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
